### ISSUE TITLE
[Build] Building Ratex with PyTorch v1.12.0

### ISSUE THREAD

**Issue by zhouyuan1119** [awslabs/ratex#6]
PyTorch has just released [v1.12.0](https://github.com/pytorch/pytorch/tree/v1.12.0) on their GitHub. As the latest stable version we might want Ratex to stick to this version for a while. Notice that if we want to use this version of PyTorch, the [Install from PYPI](https://github.com/awslabs/ratex/blob/main/docs/QUICKSTART.md#12a-install-pytorch-from-pypi-recommanded) solution in [QUICKSTART.md](https://github.com/awslabs/ratex/blob/main/docs/QUICKSTART.md) does not seem to work right now because the latest libtorch version is already 1.13. This should work after PyTorch releases the stable libtorch v1.12, but right now if we want to use Ratex we need build PyTorch from source. 

I tried to build and run Ratex with this version of PyTorch today. Here is the list of problems I have encountered and some of my fixes. 

**Build Setup**
- Ubuntu 18.04 with Anaconda 3 and CUDA 11.3.
- Build PyTorch from source using v1.12.0 on GitHub, then build Ratex on top of it. 

**Issues and Fixes**
Here I follow the steps in [QUICKSTART.md](https://github.com/awslabs/ratex/blob/main/docs/QUICKSTART.md). 

*1. Undefined symbol error when installing RAF.*
Unfortunately I cannot find the original error message, but by looking at the name of the symbol the error should come from the linker when it tries to link RAF with CUDNN. I have found that [build_third_party.sh](https://github.com/awslabs/ratex/blob/main/scripts/build_third_party.sh) uses the `USE_CUDA` env variable that was set to `0` when building PyTorch. If we don't unset this env variable, the RAF build won't use CUDA. RAF can be successfully built and imported after unsetting the env variable. 

*2. The patch file `./patches/apply_patch.sh` no longer exists under `ratex`.*

*3. PyTorch codegen script location has changed.*
```
/home/ubuntu/anaconda3/envs/ratex/bin/python3: Error while finding module specification for 'tools.codegen.gen_backend_stubs' (ModuleNotFoundError: No module named 'tools.codegen')
Failed to generate ATEN bindings: ['/home/ubuntu/ratex/ratex/scripts/generate_code.sh']
```
This file no longer exists. Looking at file names it has been moved to `torchgen/gen_backend_stubs.py`. Changing `generate_code.sh` to use the updated path instead. 

*4. Unsupported operators.*
PyTorch seems to have changed or removed the support of `max_unpool2d_backward` and `max_unpool3d_backward`. The error message is:
```
+ python3 -m torchgen.gen_backend_stubs --output_dir=/home/ubuntu/ratex/ratex/scripts/../ratex/csrc --source_yaml=/home/ubuntu/ratex/ratex/scripts/../raf_native_functions.yaml --impl_path=/home/ubuntu/ratex/ratex/scripts/../ratex/csrc/aten_raf_type.cpp
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/ratex/pytorch/torchgen/gen_backend_stubs.py", line 557, in <module>
    main()
  File "/home/ubuntu/ratex/pytorch/torchgen/gen_backend_stubs.py", line 304, in main
    run(options.source_yaml, options.output_dir, options.dry_run, options.impl_path)
  File "/home/ubuntu/ratex/pytorch/torchgen/gen_backend_stubs.py", line 498, in run
    source_yaml, grouped_native_functions, backend_indices
  File "/home/ubuntu/ratex/pytorch/torchgen/gen_backend_stubs.py", line 143, in parse_backend_yaml
    use_device_guard=use_device_guard,
  File "/home/ubuntu/ratex/pytorch/torchgen/gen_backend_stubs.py", line 118, in create_backend_index
    ), f"Found an invalid operator name: {op_name}"
AssertionError: Found an invalid operator name: max_unpool2d_backward
Failed to generate ATEN bindings: ['/home/ubuntu/ratex/ratex/scripts/generate_code.sh']
```
My dirty solution is to directly remove them from Ratex:
- Comment out the corresponding lines in `raf_native_functions.yaml`;
- Comment out their corresponding functions in `ratex/csrc/aten_raf_type.cpp`;
- In `ratex/lazy_tensor_core/csrc/ops/max_unpool_nd_backward.cpp`, comment all but the default case in the first function. 

*5. Function override error*
Some functions in PyTorch `TensorImpl` are no longer marked virtual so we cannot override them. The error message is:
```
In file included from /home/ubuntu/ratex/ratex/ratex/lazy_tensor_core/csrc/aten_ltc_bridge.cpp:16:0:
/home/ubuntu/ratex/ratex/ratex/lazy_tensor_core/csrc/tensor_impl.h:43:19: error: ‘at::IntArrayRef torch_lazy_tensors::LTCTensorImpl::sizes() const’ marked ‘override’, but does not override
   at::IntArrayRef sizes() const override;
                   ^~~~~
/home/ubuntu/ratex/ratex/ratex/lazy_tensor_core/csrc/tensor_impl.h:45:11: error: ‘int64_t torch_lazy_tensors::LTCTensorImpl::dim() const’ marked ‘override’, but does not override
   int64_t dim() const override;
           ^~~
/home/ubuntu/ratex/ratex/ratex/lazy_tensor_core/csrc/tensor_impl.h:47:11: error: ‘int64_t torch_lazy_tensors::LTCTensorImpl::numel() const’ marked ‘override’, but does not override
   int64_t numel() const override;
           ^~~~~
/home/ubuntu/ratex/ratex/ratex/lazy_tensor_core/csrc/tensor_impl.h:49:8: error: ‘bool torch_lazy_tensors::LTCTensorImpl::is_contiguous(c10::MemoryFormat) const’ marked ‘override’, but does not override
   bool is_contiguous(at::MemoryFormat memory_format) const override;
        ^~~~~~~~~~~~~
/home/ubuntu/ratex/ratex/ratex/lazy_tensor_core/csrc/tensor_impl.h:51:11: error: ‘int64_t torch_lazy_tensors::LTCTensorImpl::size(int64_t) const’ marked ‘override’, but does not override
   int64_t size(int64_t d) const override;
```
I simply remove the `override` keywords from Ratex's function declarations in `ratex/lazy_tensor_core/csrc/tensor_impl.h`. 

*6. Packages `glob2` and `filelock` are not installed when using `build_ratex.sh`.*
 [build_ratex.sh](https://github.com/awslabs/ratex/blob/main/scripts/build_ratex.sh) does not seem to install these two packages automatically. Must install them before importing Ratex. With the fixes above Ratex builds with PyTorch v1.12.0. 

*7. Running the LeNet example.*
The LeNet example cannot be run because the shape of the input data tensor becomes `[0]` right after `input.to("lazy")` is called. Error message is:
```
/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
raf starts...
Epoch 0/9
----------
Traceback (most recent call last):
  File "lenet.py", line 167, in <module>
    main()
  File "lenet.py", line 153, in main
    train("lazy", model_mnm, image_datasets)
  File "lenet.py", line 77, in train
    outputs = model(inputs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/ratex/utils/utils.py", line 49, in _timer
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/ratex/jit/script.py", line 276, in wrapper
    ) = convert_module_to_raf(module, shape_n_dtype, args)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/ratex/utils/utils.py", line 49, in _timer
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/ratex/jit/script.py", line 181, in wrapper
    value = wrapped_func(module, shape_n_dtype, args)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/ratex/jit/script.py", line 208, in convert_module_to_raf
    model = raf.frontend.from_pytorch(cloned_module, {"input0": shape_n_dtype})
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/raf/frontend/pytorch.py", line 156, in from_pytorch
    scripted_model = trace_model(model, shape_dict)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/raf/frontend/pytorch.py", line 107, in trace_model
    scripted_model = inner(model, shape_dict)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/raf/frontend/pytorch.py", line 99, in inner
    scripted_model = torch.jit.trace(model, tuple(example_inputs)).eval()
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/jit/_trace.py", line 759, in trace
    _module_class,
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/jit/_trace.py", line 974, in trace_module
    argument_names,
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/raf/frontend/pytorch.py", line 52, in forward
    out = self.model(*inputs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "lenet.py", line 34, in forward
    out = self.conv1(x)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/ratex/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [0]
```
Right now I don't have any idea about why this is happening. Running native PyTorch on CPU produces the correct outputs. Any suggestions are welcome.

**Comment by comaniac** [comment]
Thanks for the investigation. It's indeed helpful!
I believe (1) should not be an issue, and (2) was removed by me intentionally exactly for supporting PT v1.12.

3-5 are indeed the compatibility issue that we should fix, and your fixes mostly make sense to me.
6 is straightforward.
7 needs more investigations.

I'll firstly create a nightly docker image with PT v1.12 release, and we could create a branch for all fixes. Once all fixes are finalized, we could just tag the nightly image as the latest one. Since then, Ratex supports PT v1.12 stable release.

**Comment by comaniac** [comment]
Docker image has been pushed for testing: `metaprojdev/ratex:ci_gpu-pt1.12`
